apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-prod-env
data:
  prod.env: |
    # PORT=""
    PROJECT_NAME="Zerohertz's FastAPI Boilerplate (prod)"
    VERSION="v0.0.1"
    PREFIX=""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  TYPE: "mysql+asyncmy"
  HOST: "mysql"
  PORT: "3306"
  DATABASE: "fastapi"
