apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: ROOT_PASSWORD
            # WARN: mysql:8.0 사용 시 MYSQL_PWD를 설정하면 아래 오류가 발생한다.
            # error: 'Access denied for user 'root'@'localhost' (using password: YES)'
            # - name: MYSQL_PWD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mysql
            #       key: ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: USER_NAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: USER_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql
                  key: DATABASE
          ports:
            - containerPort: 3306
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  mysqladmin -h 127.0.0.1 status
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  mysqladmin -h 127.0.0.1 ping
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          hostPath:
            path: /data/mysql/fastapi-cookbook
            type: DirectoryOrCreate
# References: https://github.com/bitnami/charts/blob/78bbe94ec731a0cb046e0387b5d610de41f97472/bitnami/mysql/templates/primary/statefulset.yaml#L247-L275
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  ClusterIP: None
