apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-env
data:
  dev.env: |
    ENV="DEV"
    PORT="8000"
    PROJECT_NAME="Zerohertz's FastAPI Cookbook (dev)"
    VERSION="v0.1.1"
    PREFIX="/api"
    TZ="Asia/Seoul"
    DB_ECHO=true
    DB_TABLE_CREATE=true
  prod.env: |
    ENV="PROD"
    PORT="8000"
    PROJECT_NAME="Zerohertz's FastAPI Cookbook (prod)"
    VERSION="v0.1.1"
    PREFIX=""
    TZ="Asia/Seoul"
    DB_ECHO=false
    DB_TABLE_CREATE=false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql
data:
  TYPE: "postgresql"
  DRIVER: "asyncpg"
  HOST: "postgresql"
  PORT: "5432"
  DATABASE: "fastapi"
