apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: zerohertzkr/fastapi-cookbook:177edc64be658411baf0d47e79928e93ca4d8966
          env:
            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: postgresql
                  key: TYPE
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: postgresql
                  key: DRIVER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgresql
                  key: HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgresql
                  key: PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: USER_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: USER_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgresql
                  key: DATABASE
            - name: GITHUB_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: PROD_CLIENT_ID
            - name: GITHUB_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: PROD_CLIENT_SECRET
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: JWT_SECRET_KEY
            - name: JWT_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: JWT_ALGORITHM
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: fastapi-prod-env-volume
              mountPath: /workspace/envs
      volumes:
        - name: fastapi-prod-env-volume
          configMap:
            name: fastapi-env
            items:
              - key: prod.env
                path: prod.env
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  ports:
    - port: 8000
  selector:
    app: fastapi
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fasapi
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.zerohertz.xyz`)
      kind: Rule
      services:
        - name: fastapi
          port: 8000
  tls:
    certResolver: zerohertz-resolver
