name: "CD"

on:
  push:
    tags:
      - "v*"

jobs:
  image-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set tag based on ref
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "Tag name is $TAG_NAME"
          else
            TAG_NAME=${GITHUB_SHA}
            echo "Using commit SHA as tag: $TAG_NAME"
          fi
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fastapi-cookbook:latest,
            ${{ secrets.DOCKER_USERNAME }}/fastapi-cookbook:${{ env.tag_name }},
            ghcr.io/${{ secrets.GH_USERNAME }}/fastapi-cookbook:latest,
            ghcr.io/${{ secrets.GH_USERNAME }}/fastapi-cookbook:${{ env.tag_name }}

      - name: Slack webhook
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: fastapi-cookbook
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_CHECK }}
        if: always()

  # argo-cd:
  #   name: Argo CD
  #   needs: image-build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.GH_TOKEN }}
  #
  #     - name: Change manifest
  #       run: |
  #         sed -i 's|${{ secrets.DOCKER_USERNAME }}/fastapi-cookbook:[^ ]*|${{ secrets.DOCKER_USERNAME }}/fastapi-cookbook:${{ env.tag_name }}|' k8s/postgresql/fastapi.yaml
  #
  #     - name: git push
  #       run: |
  #         git config user.name ${{ secrets.GH_USERNAME }}
  #         git config user.email "ohg3417@gmail.com"
  #         git config credential.helper store
  #         git add k8s/postgresql/fastapi.yaml
  #         git commit -m ":tada: deploy: fastapi-cookbook [${{ env.tag_name }}]"
  #         git fetch origin
  #         git checkout -b main origin/main
  #         git push origin main
  #
  #     - name: Slack webhook
  #       uses: 8398a7/action-slack@v3
  #       with:
  #         status: ${{ job.status }}
  #         author_name: fastapi-cookbook
  #         fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
  #         if_mention: failure,cancelled
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_CHECK }}
  #       if: always()
